### ISSUE TITLE
Quality of Life Improvements

### ISSUE THREAD

**Issue by GollyTicker** [qaware/protocurl#11]
Avoid explicitly specifying the file via -f and instead search the message types from -i and -o. Additionally, it should be sufficient to only use the name of the message type instead of the full path, whenever the message type is unique.

- [x] user feedback/iteration and tests
- [x] implementation
- [x] update documentation

**Comment by qa-swaneet-sahoo** [comment]
We still need to update the usage text to the new functionality.

**Comment by qa-swaneet-sahoo** [comment]
Documentation updated on main
