### ISSUE TITLE
Example for GET requests without request-type and data-text

### ISSUE THREAD

**Issue by vishal24tuniki** [qaware/protocurl#129]
I am trying to invoke an API endpoint whose http method is GET and doesn't have any request body but response body is binary (protobuf)

Struggling to use protocurl for above use case. Request help here

**Comment by GollyTicker** [comment]
Currently, [only HTTP POST requests are possible with protocurl](https://github.com/qaware/protocurl/blob/main/src/httpRequest.go#L70). It seems like me and the other users never yet thought about supporting other http methods. :sweat_smile: 

Thanks for the hint towards the get request.

I'll adapt the test server and check, how much modification is needed to support this. I think its rather a small change.

I'll consider the following test cases. Please tell me, if these are sufficient from your side:
* GET request with no url-data and an empty response
* GET request with too long URL-data which fails on HTTP protocol level
* GET request with long URL-data and a non-empty response

I wonder what the best way is to sepcify which method shall be used. Currently, the method is hard coded as `POST` (as you see in he above link). We need to think of a good command line argument for that. We could add a flag `-X` or `-m/--method` and use it like `protocurl -X GET <other-args> -u <url>`. On the other hand, I don't know, how common it is to use PUT, DELETE, PATCH, etc. with protobuf payloads. I am not sure whether it makes sense to optimistically support it (ie. just forward the method argument to curl) or to only support POST+GET (which are thoroughly tested in the tests).

What do you think?

**Comment by vishal24tuniki** [comment]
Hi @GollyTicker 

Sorry, i have been away.

The test cases looks good. Using `-X` make it compatible with normal curl. So we can go ahead with it. If other methods can be supported, i feel we should just go for it now itself as long as it's just forwarding the method as is to curl.

**Comment by GollyTicker** [comment]
@vishal24tuniki Sorry for me delayed response. I was gone on a long vacation.

I'll check back and make a small implementation without tests which you can use. We can add tests afterwards then. Except a response within the next 1-2 weeks.

**Comment by ilya-rusyanov** [comment]
Are there any updates on it? Also need the GET functionality....

**Comment by GollyTicker** [comment]
@vishal24tuniki @ilya-rusyanov 

I had forgotten to look back into this. Sorry.

I've created an untested preliminary release (https://github.com/qaware/protocurl/releases/tag/v1.7.1-rc1) which simply passes on the `-X METHOD` to curl. Simply use the `-X` argument and you should be able to send GET requests.

In the next days I'll add the tests for GET and make a proper release. The current implementation will also support DELETE, PATCH, etc. but only optimistically (without specific tests for them).

Is this enough for you to continue on your side?

**Comment by ilya-rusyanov** [comment]
Tested it with 

```bash
protocurl -X GET -I ./spec -o ..MyType -u http://localhost:8080/path/to/endpoint 
````

and getting 

> Error: required flag(s) "data-text", "request-type" not set

 Am I missing something?

**Comment by GollyTicker** [comment]
@ilya-rusyanov 

Ah, correct. I had missed to update the mandatory body requirement.

Please try the new rc: https://github.com/qaware/protocurl/releases/tag/v1.7.1-rc2

**Comment by GollyTicker** [comment]
@ilya-rusyanov @vishal24tuniki 

Please take a look at the new release candidate, and tell me, if you need anything more: https://github.com/qaware/protocurl/releases/tag/v1.8.0-rc

The usage text should be sufficient: https://github.com/qaware/protocurl/blob/129-get-requests/doc/generated.usage.txt

**Comment by ilya-rusyanov** [comment]
> Please take a look at the new release candidate, and tell me, if you need anything more: https://github.com/qaware/protocurl/releases/tag/v1.8.0-rc

Works as expected! Many thanks!!

**Comment by GollyTicker** [comment]
Released in https://github.com/qaware/protocurl/releases/tag/v1.8.0
