### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by vladraduvidican** [qaware/protocurl#170]
Hello! I'd love to use protocurl, but without any other logging. I know -q suppresses the sent data, but I'd love to have no output and input at all.

**Comment by GollyTicker** [comment]
Hi @vladraduvidican!

Thanks for your suggesiton. I can add a new option `-s` / `--silent` which also doesn't output any response. But do you also want to supress the error output on stderr or not? If so, then using `-s` would be equivalent to piping stdout and stderr to /dev/null and only the exitcode would give any information on what happend.

**Comment by vladraduvidican** [comment]
In my specific case I'd like to have stderr output unchanged, but if you consider it makes more sense to also mute stderr it's okay. Thanks a lot!

**Comment by GollyTicker** [comment]
@vladraduvidican 

Let me know, if this is good for you.

https://github.com/qaware/protocurl/releases/tag/v1.9.0-rc

**Comment by GollyTicker** [comment]
@vladraduvidican ping 😇

**Comment by vladraduvidican** [comment]
Thanks a lot! I apologise for the late response, I was not home.
