### ISSUE TITLE
How to send file as payload ? 

### ISSUE THREAD

**Issue by Ishmeet** [qaware/protocurl#173]
I tried `-d @payload.json `, but it didn't work

```
protocurl -I . -i ..ARequest -o ..AResponse -u localhost:9443/send -d @payload.json
Warning: Couldn't read data from file "payload.json", this makes an 
Warning: empty POST.
```

**Comment by GollyTicker** [comment]
@Ishmeet ping 😇

**Comment by Ishmeet** [comment]
@GollyTicker ,
Yes definitely, it will be good improvement to add `-d @<filepath>`.

**Comment by GollyTicker** [comment]
@Ishmeet 

I have not much time ATM and in near future.

Can you perhaps add it yourself? You'll have it much earlier then.

What do you think? The repository is well documented. Nevertheless, if you have questions you can ask.

**Comment by Ishmeet** [comment]
> @Ishmeet . Ok
> 
> Unfortunately, I have not much time atm and in near future.
> 
> Can you perhaps add it yourself? You'll have it much earlier then.
> 
> What do you think? The repository is well documented. Nevertheless, if you have questions you can ask.

I'll try

**Comment by GollyTicker** [comment]
@Ishmeet 

Did you manage to take a look at it? 😇

**Comment by Ishmeet** [comment]
@GollyTicker , I finally got time to work on this.
Would appreciate ur review https://github.com/qaware/protocurl/pull/181

**Comment by GollyTicker** [comment]
Thanks for your effort! I took a look at it! :tada:
