### ISSUE TITLE
Reduce security scan vulnerabilities

### ISSUE THREAD

**Issue by qa-swaneet-sahoo** [qaware/protocurl#27]
Vulnerabilities: https://github.com/qaware/protocurl/runs/6076743051?check_suite_focus=true
(check security scan step)

See #26

**Comment by qa-swaneet-sahoo** [comment]
Open questions:
* We need to include curl in the image, since otherwise protocurl will not be feature-full. However, it is not clear how, we might pick a correct version of curl without any known high security vulnerabilities.

**Comment by GollyTicker** [comment]
Closed by #26
