### ISSUE TITLE
Check and ensure adherence to Protobuf Specification

### ISSUE THREAD

**Issue by GollyTicker** [qaware/protocurl#31]
The [Protobuf Language Guide](https://developers.google.com/protocol-buffers/docs/proto3) and the [Reference](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec) as well as the [well-known types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf) are the source of truths for the kinds of functionality protoCURL should support.

During development and before, I haven't read through the entire guide, or all well-known types or the spec. This means, that I might be missing important capabilities of protobuf. To ensure a fully compliant solution, the implementation should work with all aspects mentioned in the guide, spec and well-known types.

**Comment by qa-swaneet-sahoo** [comment]
Since the tool is mostly simply a wrapper around curl/http and the Go protobuf SDK, we think it does not make much sense to heavily test this. If sophisticated stuff happens, then these tests will be justified.
