### ISSUE TITLE
Split go sources into packages

### ISSUE THREAD

**Issue by qa-swaneet-sahoo** [qaware/protocurl#35]
Due to simplicity, currently everything is in the main package. When the complexity of the code gets larger it may make sense, to split the go source into multiple packages and sub-directories. In that case, we also need to take care of the capitalization, since only objects starting uppercase will be publically visible: https://go.dev/doc/effective_go

**Comment by qa-swaneet-sahoo** [comment]
At the current moment, the complexity is limited and a restructuring is not necessary.

**Comment by GollyTicker** [comment]
This'll remain low complexity for a long while, so we'll not fix this.
