### ISSUE TITLE
 unmarshal unknown message 

### ISSUE THREAD

**Issue by 89z** [qaware/protocurl#51]
Is it possible to Unmarshal an unknown message, given some arbitrary input bytes? Similar to `json.Unmarshal`

**Comment by GollyTicker** [comment]
Hi,

Do I understand correctly, that your service returns a protobuf payload - but you don't know which schema it belongs to - so you want to see the fields numbers and values of the raw payload in a textual format? If this is the case, then the issue #10 is open - which aims to solve exactly this problem. I was waiting for feedback from users to know, if I need to prioritize this. If you agree, then I can could on that feature.

With `json.Unmarshal`, do you mean this [jsonpb.Unmarshal](https://pkg.go.dev/github.com/golang/protobuf/jsonpb#Unmarshaler.Unmarshal)? I have no experience with this method - and looking at the documentation and skimming through the implementation does not make it immediately clear to me if and how it can process unknown messages.

If none of both is what you mean, then could you elaborate on your problem?

**Comment by 89z** [comment]
> Do I understand correctly, that your service returns a protobuf payload - but you don't know which schema it belongs to - so you want to see the fields numbers and values of the raw payload in a textual format?

Its not my service, but a response from a public server.

> With `json.Unmarshal`, do you mean this [jsonpb.Unmarshal](https://pkg.go.dev/github.com/golang/protobuf/jsonpb#Unmarshaler.Unmarshal)?

No, this one:

https://godocs.io/encoding/json#Unmarshal

With JSON, you can do something like this:

~~~go
package main

import (
   "encoding/json"
   "fmt"
)

var buf = []byte(`
{
   "this": {
      "is": {
         "some": {"arbitrary": "bytes"}
      }
   }
}
`)

func main() {
   var mes map[string]any
   json.Unmarshal(buf, &mes)
   fmt.Println(mes) // map[this:map[is:map[some:map[arbitrary:bytes]]]]
}
~~~

**Comment by GollyTicker** [comment]
Thanks for the clarification. It seems, that this use case is covered by #10.

Do you have any request/problem which is not covered by the above issue? If not, then you can close the current issue.
